// Las 1000 frases más usadas del inglés cotidiano: [inglés, español].
// Ordenadas por temas de uso diario; las practica la sección 📚 1000 frases.
'use strict';
const P1K = [
["Hi, how are you?","Hola, ¿cómo estás?"],
["Hello! Nice to meet you.","¡Hola! Mucho gusto."],
["Good morning!","¡Buenos días!"],
["Good afternoon!","¡Buenas tardes!"],
["Good evening!","¡Buenas noches! (al llegar)"],
["Hey, what's up?","Oye, ¿qué más?"],
["How's it going?","¿Cómo te va?"],
["How have you been?","¿Cómo has estado?"],
["Long time no see!","¡Tanto tiempo sin verte!"],
["What's your name?","¿Cómo te llamas?"],
["My name is David.","Me llamo David."],
["I'm from Colombia.","Soy de Colombia."],
["Where are you from?","¿De dónde eres?"],
["Nice to meet you too.","Mucho gusto también."],
["How old are you?","¿Cuántos años tienes?"],
["I'm twenty years old.","Tengo veinte años."],
["This is my friend.","Este es mi amigo."],
["Have we met before?","¿Nos conocemos de antes?"],
["I've heard a lot about you.","He oído mucho de ti."],
["Welcome!","¡Bienvenido!"],
["Come on in.","Sigue, entra."],
["Make yourself at home.","Siéntete como en casa."],
["It's a pleasure.","Es un placer."],
["Pleased to meet you.","Encantado de conocerte."],
["How do you do?","¿Cómo está usted?"],
["What do you do?","¿A qué te dedicas?"],
["I'm a student.","Soy estudiante."],
["Do you speak English?","¿Hablas inglés?"],
["I speak a little English.","Hablo un poco de inglés."],
["I'm learning English.","Estoy aprendiendo inglés."],
["Where do you live?","¿Dónde vives?"],
["I live in the city.","Vivo en la ciudad."],
["Nice to see you again.","Qué bueno verte de nuevo."],
["What brings you here?","¿Qué te trae por aquí?"],
["How was your day?","¿Cómo estuvo tu día?"],
["It's good to see you.","Qué gusto verte."],
["Anyone here?","¿Hay alguien aquí?"],
["Is this seat taken?","¿Está ocupado este asiento?"],
["Mind if I join you?","¿Te molesta si me uno?"],
["I like your style.","Me gusta tu estilo."],
["Thank you so much.","Muchísimas gracias."],
["Thanks a lot.","Muchas gracias."],
["You're welcome.","De nada."],
["No problem.","No hay problema."],
["Don't worry about it.","No te preocupes por eso."],
["Excuse me, please.","Disculpa, por favor."],
["I'm so sorry.","Lo siento mucho."],
["My bad.","Fue mi culpa."],
["It's okay.","Está bien."],
["No worries.","Tranquilo, no pasa nada."],
["Can I help you?","¿Te puedo ayudar?"],
["Of course.","Por supuesto."],
["Sure, go ahead.","Claro, adelante."],
["After you.","Después de ti."],
["Bless you!","¡Salud! (estornudo)"],
["Congratulations!","¡Felicitaciones!"],
["Happy birthday!","¡Feliz cumpleaños!"],
["Good luck!","¡Buena suerte!"],
["Have a good one.","Que te vaya bien."],
["That's very kind of you.","Muy amable de tu parte."],
["I appreciate it.","Te lo agradezco."],
["Sorry to bother you.","Perdón por molestarte."],
["May I come in?","¿Puedo entrar?"],
["Please, have a seat.","Por favor, toma asiento."],
["Help yourself.","Sírvete tú mismo."],
["Sorry, I didn't mean it.","Perdón, no fue mi intención."],
["Excuse me for a moment.","Discúlpame un momento."],
["I owe you one.","Te debo una."],
["Thanks for everything.","Gracias por todo."],
["Thanks for your help.","Gracias por tu ayuda."],
["Goodbye!","¡Adiós!"],
["Bye, see you later!","¡Chao, nos vemos!"],
["See you tomorrow.","Nos vemos mañana."],
["See you soon.","Hasta pronto."],
["See you around.","Nos estamos viendo."],
["Take care!","¡Cuídate!"],
["Have a nice day!","¡Que tengas un buen día!"],
["Have a good weekend!","¡Buen fin de semana!"],
["Good night, sleep well.","Buenas noches, que descanses."],
["I have to go now.","Ya me tengo que ir."],
["I'm leaving now.","Ya me voy."],
["It was nice talking to you.","Fue un gusto hablar contigo."],
["Talk to you later.","Hablamos luego."],
["Catch you later.","Nos vemos luego."],
["I'll be right back.","Ya vuelvo."],
["I'm off to bed.","Me voy a dormir."],
["Say hi to your family.","Saluda a tu familia."],
["Keep in touch.","Sigamos en contacto."],
["Safe travels!","¡Buen viaje!"],
["Until next time.","Hasta la próxima."],
["I really enjoyed this.","De verdad lo disfruté."],
["Don't be a stranger.","No te pierdas."],
["It's getting late.","Se está haciendo tarde."],
["I should get going.","Debería irme ya."],
["Nice weather today, right?","Buen clima hoy, ¿no?"],
["How's your family?","¿Cómo está tu familia?"],
["What's new?","¿Qué hay de nuevo?"],
["Not much, you?","Nada especial, ¿y tú?"],
["Same as always.","Lo mismo de siempre."],
["How's work going?","¿Cómo va el trabajo?"],
["Busy day, huh?","Día ocupado, ¿no?"],
["Any plans for the weekend?","¿Planes para el fin de semana?"],
["Did you sleep well?","¿Dormiste bien?"],
["What have you been up to?","¿Qué has hecho últimamente?"],
["You look great today.","Te ves muy bien hoy."],
["Time flies, doesn't it?","El tiempo vuela, ¿no?"],
["Small world!","¡Qué pequeño es el mundo!"],
["Speak of the devil.","Hablando del rey de Roma."],
["That reminds me of something.","Eso me recuerda algo."],
["By the way...","Por cierto..."],
["Guess what?","¿Adivina qué?"],
["You won't believe this.","No vas a creer esto."],
["Have you heard the news?","¿Supiste la noticia?"],
["What do you think about that?","¿Qué opinas de eso?"],
["Let me tell you something.","Déjame contarte algo."],
["That's a long story.","Esa es una historia larga."],
["To make a long story short...","Para resumir..."],
["Anyway, moving on.","En fin, sigamos."],
["Where was I?","¿En qué iba?"],
["As I was saying...","Como iba diciendo..."],
["That's so true.","Eso es muy cierto."],
["Tell me more.","Cuéntame más."],
["And then what happened?","¿Y luego qué pasó?"],
["No way, really?","¿En serio? ¡No puede ser!"],
["Are you serious?","¿Hablas en serio?"],
["You're kidding me.","Me estás tomando el pelo."],
["I'm just kidding.","Solo estoy bromeando."],
["Just joking!","¡Es broma!"],
["That's hilarious.","Qué chistoso."],
["That made my day.","Eso me alegró el día."],
["What a coincidence!","¡Qué coincidencia!"],
["It is what it is.","Es lo que hay."],
["Such is life.","Así es la vida."],
["Believe it or not.","Aunque no lo creas."],
["Honestly speaking...","Hablando en serio..."],
["Between you and me...","Entre tú y yo..."],
["What time is it?","¿Qué hora es?"],
["What day is today?","¿Qué día es hoy?"],
["Where are you going?","¿A dónde vas?"],
["What are you doing?","¿Qué estás haciendo?"],
["What's going on?","¿Qué está pasando?"],
["What happened?","¿Qué pasó?"],
["What's wrong?","¿Qué pasa? ¿Qué tienes?"],
["Are you okay?","¿Estás bien?"],
["Can you help me?","¿Me puedes ayudar?"],
["Could you repeat that, please?","¿Puedes repetir, por favor?"],
["Can you speak slower?","¿Puedes hablar más despacio?"],
["What does that mean?","¿Qué significa eso?"],
["How do you say this in English?","¿Cómo se dice esto en inglés?"],
["How do you spell that?","¿Cómo se escribe eso?"],
["Did you understand?","¿Entendiste?"],
["Do you understand me?","¿Me entiendes?"],
["What do you mean?","¿Qué quieres decir?"],
["Why not?","¿Por qué no?"],
["Why is that?","¿Y eso por qué?"],
["How come?","¿Cómo así?"],
["Says who?","¿Según quién?"],
["Are you sure?","¿Estás seguro?"],
["Really?","¿De verdad?"],
["Is that true?","¿Eso es cierto?"],
["Who told you that?","¿Quién te dijo eso?"],
["Where did you hear that?","¿Dónde oíste eso?"],
["May I ask you something?","¿Te puedo preguntar algo?"],
["Can I ask you a favor?","¿Te puedo pedir un favor?"],
["Do you have a minute?","¿Tienes un minuto?"],
["What do you need?","¿Qué necesitas?"],
["Is everything okay?","¿Todo bien?"],
["What's the matter?","¿Qué ocurre?"],
["Am I right?","¿Tengo razón?"],
["You know what I mean?","¿Me entiendes? ¿Sí o qué?"],
["Does that make sense?","¿Tiene sentido?"],
["What should I do?","¿Qué debería hacer?"],
["What would you do?","¿Tú qué harías?"],
["Can I try?","¿Puedo intentar?"],
["Whose is this?","¿De quién es esto?"],
["What is this called?","¿Cómo se llama esto?"],
["How does this work?","¿Cómo funciona esto?"],
["Where can I find it?","¿Dónde lo puedo encontrar?"],
["Which one do you prefer?","¿Cuál prefieres?"],
["What's your favorite?","¿Cuál es tu favorito?"],
["Anything else?","¿Algo más?"],
["Is that all?","¿Eso es todo?"],
["Yes, of course.","Sí, claro."],
["No, thanks.","No, gracias."],
["Yes, please.","Sí, por favor."],
["Maybe later.","Quizás más tarde."],
["I think so.","Creo que sí."],
["I don't think so.","Creo que no."],
["I'm not sure.","No estoy seguro."],
["I have no idea.","No tengo ni idea."],
["I don't know.","No sé."],
["Who knows?","¿Quién sabe?"],
["It depends.","Depende."],
["More or less.","Más o menos."],
["Kind of.","Algo así."],
["Not really.","La verdad, no."],
["Not at all.","Para nada."],
["Absolutely!","¡Totalmente!"],
["Definitely.","Definitivamente."],
["Exactly!","¡Exacto!"],
["That's right.","Así es."],
["You're right.","Tienes razón."],
["I guess so.","Supongo que sí."],
["I hope so.","Eso espero."],
["I hope not.","Espero que no."],
["Me too.","Yo también."],
["Me neither.","Yo tampoco."],
["Same here.","Igual yo."],
["Sounds good.","Suena bien."],
["Sounds like a plan.","Me parece buen plan."],
["Fine by me.","Por mí está bien."],
["Whatever you say.","Como tú digas."],
["Up to you.","Como quieras, tú decides."],
["It doesn't matter.","No importa."],
["Never mind.","Olvídalo."],
["Forget it.","Déjalo así."],
["That works for me.","Eso me funciona."],
["Deal!","¡Trato hecho!"],
["No doubt about it.","Sin duda alguna."],
["I totally agree.","Estoy totalmente de acuerdo."],
["I disagree.","No estoy de acuerdo."],
["That's not true.","Eso no es cierto."],
["You've got a point.","Tienes un buen punto."],
["Fair enough.","Me parece justo."],
["Good point.","Buen punto."],
["That makes sense.","Eso tiene sentido."],
["That doesn't make sense.","Eso no tiene sentido."],
["I see your point.","Entiendo tu punto."],
["Let's agree to disagree.","Aceptemos que pensamos distinto."],
["I couldn't agree more.","No podría estar más de acuerdo."],
["That's debatable.","Eso es discutible."],
["I'm on your side.","Estoy de tu lado."],
["Trust me.","Confía en mí."],
["I promise.","Te lo prometo."],
["I swear.","Te lo juro."],
["Cross my heart.","Palabra de honor."],
["I mean it.","Lo digo en serio."],
["I'm telling the truth.","Digo la verdad."],
["Prove it.","Demuéstralo."],
["I doubt it.","Lo dudo."],
["We'll see.","Ya veremos."],
["Time will tell.","El tiempo lo dirá."],
["I think it's a good idea.","Creo que es una buena idea."],
["In my opinion...","En mi opinión..."],
["If you ask me...","Si me preguntas a mí..."],
["From my point of view...","Desde mi punto de vista..."],
["I believe so.","Así lo creo."],
["As far as I know...","Hasta donde sé..."],
["It seems to me that...","Me parece que..."],
["I have a feeling.","Tengo un presentimiento."],
["I love it!","¡Me encanta!"],
["I like it a lot.","Me gusta mucho."],
["I don't like it.","No me gusta."],
["I hate it.","Lo odio."],
["It's not my thing.","No es lo mío."],
["It's not bad.","No está mal."],
["It could be better.","Podría ser mejor."],
["It could be worse.","Podría ser peor."],
["That's amazing!","¡Eso es increíble!"],
["That's awesome!","¡Qué genial!"],
["That's incredible.","Es increíble."],
["That's wonderful.","Es maravilloso."],
["That's terrible.","Eso es terrible."],
["That's awful.","Qué horrible."],
["That's weird.","Qué raro."],
["That's strange.","Qué extraño."],
["That's interesting.","Qué interesante."],
["That's boring.","Qué aburrido."],
["How cool is that?","¿Qué tan genial es eso?"],
["This is the best!","¡Esto es lo mejor!"],
["This is the worst.","Esto es lo peor."],
["Better than nothing.","Mejor que nada."],
["Not bad at all.","Nada mal."],
["Pretty good, actually.","Bastante bien, de hecho."],
["It's worth it.","Vale la pena."],
["It's not worth it.","No vale la pena."],
["I'm impressed.","Estoy impresionado."],
["I expected more.","Esperaba más."],
["It's too much.","Es demasiado."],
["It's not enough.","No es suficiente."],
["Way better.","Mucho mejor."],
["Way worse.","Mucho peor."],
["I'm happy.","Estoy feliz."],
["I'm so excited!","¡Estoy muy emocionado!"],
["I'm sad.","Estoy triste."],
["I'm tired.","Estoy cansado."],
["I'm exhausted.","Estoy agotado."],
["I'm bored.","Estoy aburrido."],
["I'm angry.","Estoy enojado."],
["I'm upset.","Estoy molesto."],
["I'm nervous.","Estoy nervioso."],
["I'm scared.","Tengo miedo."],
["I'm worried.","Estoy preocupado."],
["I'm confused.","Estoy confundido."],
["I'm surprised.","Estoy sorprendido."],
["I'm proud of you.","Estoy orgulloso de ti."],
["I'm in a good mood.","Estoy de buen humor."],
["I'm in a bad mood.","Estoy de mal humor."],
["I feel great.","Me siento genial."],
["I feel sick.","Me siento enfermo."],
["I don't feel well.","No me siento bien."],
["I feel much better.","Me siento mucho mejor."],
["I'm hungry.","Tengo hambre."],
["I'm thirsty.","Tengo sed."],
["I'm sleepy.","Tengo sueño."],
["I'm cold.","Tengo frío."],
["I'm hot.","Tengo calor."],
["I'm busy right now.","Estoy ocupado ahora."],
["I'm free now.","Estoy libre ahora."],
["I'm ready.","Estoy listo."],
["I'm not ready yet.","Todavía no estoy listo."],
["I'm lost.","Estoy perdido."],
["I miss you.","Te extraño."],
["I miss home.","Extraño mi casa."],
["I can't wait!","¡No puedo esperar!"],
["I'm looking forward to it.","Lo espero con ansias."],
["I'm so embarrassed.","Qué pena me da."],
["I feel bad about it.","Me siento mal por eso."],
["It hurts.","Duele."],
["I'm freaking out.","Me estoy volviendo loco."],
["I'm stressed out.","Estoy estresado."],
["Calm down.","Cálmate."],
["Take it easy.","Tómalo con calma."],
["Relax, it's fine.","Relájate, está bien."],
["Don't panic.","No entres en pánico."],
["Everything will be okay.","Todo va a estar bien."],
["It's going to be fine.","Va a salir bien."],
["Don't give up.","No te rindas."],
["Keep going!","¡Sigue adelante!"],
["You can do it!","¡Tú puedes!"],
["Come on, you got this.","Vamos, tú puedes con esto."],
["Do your best.","Da lo mejor de ti."],
["I believe in you.","Creo en ti."],
["Well done!","¡Bien hecho!"],
["Good job!","¡Buen trabajo!"],
["Great work!","¡Excelente trabajo!"],
["I'm proud of that.","Estoy orgulloso de eso."],
["That was close!","¡Estuvo cerca!"],
["Nice try.","Buen intento."],
["Better luck next time.","Mejor suerte la próxima."],
["Practice makes perfect.","La práctica hace al maestro."],
["Never give up.","Nunca te rindas."],
["It's never too late.","Nunca es demasiado tarde."],
["Look on the bright side.","Mira el lado bueno."],
["Cheer up!","¡Anímate!"],
["Hang in there.","Aguanta, resiste."],
["One step at a time.","Un paso a la vez."],
["You're doing great.","Lo estás haciendo genial."],
["Keep it up!","¡Sigue así!"],
["Don't stress about it.","No te estreses por eso."],
["It happens to everyone.","Le pasa a todos."],
["Oh my God!","¡Dios mío!"],
["No way!","¡No puede ser!"],
["Wow, that's crazy!","¡Guau, qué locura!"],
["Awesome!","¡Increíble!"],
["Unbelievable!","¡Increíble, no lo creo!"],
["Seriously?","¿En serio?"],
["For real?","¿De verdad?"],
["You're joking, right?","Estás bromeando, ¿cierto?"],
["What a surprise!","¡Qué sorpresa!"],
["I can't believe it.","No lo puedo creer."],
["That blew my mind.","Eso me voló la cabeza."],
["Watch out!","¡Cuidado!"],
["Be careful!","¡Ten cuidado!"],
["Look at that!","¡Mira eso!"],
["Check this out.","Mira esto."],
["Here we go!","¡Aquí vamos!"],
["Here we go again.","Otra vez lo mismo."],
["Let's go!","¡Vamos!"],
["Let's do this!","¡Hagámoslo!"],
["Finally!","¡Por fin!"],
["At last!","¡Al fin!"],
["What a relief!","¡Qué alivio!"],
["Thank goodness.","Menos mal."],
["Oops, my mistake.","Ups, me equivoqué."],
["Oh no, not again.","Ay no, otra vez no."],
["That's enough!","¡Ya basta!"],
["Stop it!","¡Ya para!"],
["Cut it out.","Déjalo ya."],
["Knock it off.","Ya deja eso."],
["Leave me alone.","Déjame en paz."],
["Give me a break.","Dame un respiro."],
["Are you kidding me?","¿Es en serio?"],
["You must be joking.","Debes estar bromeando."],
["What the heck?","¿Pero qué rayos?"],
["That's so cool!","¡Qué chévere!"],
["Lucky you!","¡Qué suerte la tuya!"],
["Poor thing.","Pobrecito."],
["What a shame.","Qué lástima."],
["That's too bad.","Qué mal."],
["So sad.","Muy triste."],
["Good for you!","¡Bien por ti!"],
["Way to go!","¡Así se hace!"],
["You made it!","¡Lo lograste!"],
["We did it!","¡Lo logramos!"],
["Well, well, well...","Vaya, vaya, vaya..."],
["Let me think.","Déjame pensar."],
["Let me see.","Déjame ver."],
["Let me check.","Déjame revisar."],
["Give me a second.","Dame un segundo."],
["Just a moment, please.","Un momento, por favor."],
["Hold on a second.","Espera un segundo."],
["Wait a minute.","Espera un minuto."],
["Hurry up!","¡Apúrate!"],
["Take your time.","Tómate tu tiempo."],
["There's no rush.","No hay prisa."],
["Right away.","De inmediato."],
["As soon as possible.","Lo antes posible."],
["Sooner or later.","Tarde o temprano."],
["In the meantime...","Mientras tanto..."],
["First of all...","Antes que nada..."],
["Last but not least...","Por último pero no menos importante..."],
["On the other hand...","Por otro lado..."],
["At the end of the day...","Al final del día..."],
["The thing is...","La cosa es que..."],
["To be honest...","Para ser honesto..."],
["Actually, no.","De hecho, no."],
["As a matter of fact...","De hecho..."],
["In other words...","En otras palabras..."],
["For example...","Por ejemplo..."],
["And so on.","Y así sucesivamente."],
["Long story short.","En resumen."],
["That's all.","Eso es todo."],
["That's it!","¡Eso es!"],
["That's the point.","Ese es el punto."],
["That's not the point.","Ese no es el punto."],
["Whatever.","Como sea."],
["Anyway...","En fin..."],
["So what?","¿Y qué?"],
["Who cares?","¿A quién le importa?"],
["Why bother?","¿Para qué molestarse?"],
["No wonder.","Con razón."],
["Of course not.","Claro que no."],
["Not yet.","Todavía no."],
["Not anymore.","Ya no."],
["Almost there.","Ya casi."],
["Just in case.","Por si acaso."],
["Just in time.","Justo a tiempo."],
["Once in a while.","De vez en cuando."],
["Every now and then.","De vez en cuando."],
["Most of the time.","La mayoría del tiempo."],
["From now on.","De ahora en adelante."],
["So far, so good.","Hasta ahora, todo bien."],
["Step by step.","Paso a paso."],
["Little by little.","Poco a poco."],
["One by one.","Uno por uno."],
["By the book.","Al pie de la letra."],
["Piece of cake!","¡Pan comido!"],
["Easier said than done.","Más fácil decirlo que hacerlo."],
["It's up to you.","Depende de ti."],
["It's not a big deal.","No es gran cosa."],
["Big deal!","¡Gran cosa!"],
["No big deal.","Nada del otro mundo."],
["It's a small thing.","Es algo pequeño."],
["Don't mention it.","Ni lo menciones."],
["You never know.","Nunca se sabe."],
["Better safe than sorry.","Mejor prevenir que lamentar."],
["Can you do me a favor?","¿Me haces un favor?"],
["Could you give me a hand?","¿Me echas una mano?"],
["I need your help.","Necesito tu ayuda."],
["Can you show me?","¿Me puedes mostrar?"],
["Can you teach me?","¿Me puedes enseñar?"],
["Could you explain that again?","¿Me lo explicas otra vez?"],
["Can I borrow this?","¿Me prestas esto?"],
["Can you lend me some money?","¿Me prestas algo de dinero?"],
["Would you mind helping me?","¿Te importaría ayudarme?"],
["Can you pass me that?","¿Me pasas eso?"],
["Can you open the door?","¿Puedes abrir la puerta?"],
["Can you close the window?","¿Puedes cerrar la ventana?"],
["Turn on the light, please.","Prende la luz, por favor."],
["Turn off the light, please.","Apaga la luz, por favor."],
["Can you turn it up?","¿Puedes subirle el volumen?"],
["Can you turn it down?","¿Puedes bajarle el volumen?"],
["Follow me, please.","Sígueme, por favor."],
["Come with me.","Ven conmigo."],
["Come here.","Ven acá."],
["Wait for me!","¡Espérame!"],
["Don't touch that.","No toques eso."],
["Be quiet, please.","Silencio, por favor."],
["Listen to me.","Escúchame."],
["Pay attention.","Presta atención."],
["Look at me.","Mírame."],
["Try again.","Intenta de nuevo."],
["Try it on.","Pruébatelo."],
["Give it a try.","Dale una oportunidad."],
["Let me help you.","Déjame ayudarte."],
["Let me know.","Avísame."],
["Keep me posted.","Mantenme informado."],
["Remind me later.","Recuérdamelo más tarde."],
["Write it down.","Anótalo."],
["Don't forget.","No lo olvides."],
["Bring it here.","Tráelo acá."],
["Put it there.","Ponlo ahí."],
["Leave it there.","Déjalo ahí."],
["Pick it up.","Recógelo."],
["Put it away.","Guárdalo."],
["Throw it away.","Bótalo."],
["What are you doing tonight?","¿Qué haces esta noche?"],
["Are you free tomorrow?","¿Estás libre mañana?"],
["Do you want to hang out?","¿Quieres salir un rato?"],
["Let's hang out sometime.","Salgamos algún día."],
["Do you want to come?","¿Quieres venir?"],
["Would you like to join us?","¿Te gustaría unirte?"],
["Let's meet up later.","Nos vemos más tarde."],
["Where should we meet?","¿Dónde nos encontramos?"],
["What time works for you?","¿Qué hora te sirve?"],
["How about tomorrow?","¿Qué tal mañana?"],
["See you at eight.","Nos vemos a las ocho."],
["I'll pick you up.","Paso por ti."],
["Don't be late.","No llegues tarde."],
["I'm on my way.","Voy en camino."],
["I'm almost there.","Ya casi llego."],
["I'm running late.","Voy tarde."],
["Sorry I'm late.","Perdón por llegar tarde."],
["You're right on time.","Llegaste justo a tiempo."],
["Maybe next time.","Quizás la próxima."],
["I can't make it.","No voy a poder ir."],
["I have plans already.","Ya tengo planes."],
["Let's reschedule.","Reprogramemos."],
["Can we do it another day?","¿Lo dejamos para otro día?"],
["Something came up.","Me surgió algo."],
["It's on my schedule.","Está en mi agenda."],
["What's the plan?","¿Cuál es el plan?"],
["The plan has changed.","El plan cambió."],
["Let's play it by ear.","Vamos viendo sobre la marcha."],
["Count me in!","¡Cuenta conmigo!"],
["Count me out.","No cuentes conmigo."],
["I'll think about it.","Lo voy a pensar."],
["Let me get back to you.","Luego te confirmo."],
["It's a date!","¡Quedamos así!"],
["Are you coming or not?","¿Vienes o no?"],
["I'm starving.","Me muero de hambre."],
["What's for dinner?","¿Qué hay de cena?"],
["What do you want to eat?","¿Qué quieres comer?"],
["Let's grab a bite.","Vamos a comer algo."],
["Let's order pizza.","Pidamos pizza."],
["Do you want some?","¿Quieres un poco?"],
["I'd like a coffee, please.","Un café, por favor."],
["Can I see the menu?","¿Puedo ver el menú?"],
["What do you recommend?","¿Qué recomiendas?"],
["I'll have the same.","Yo quiero lo mismo."],
["For here or to go?","¿Para comer aquí o para llevar?"],
["To go, please.","Para llevar, por favor."],
["The check, please.","La cuenta, por favor."],
["It's on me.","Yo invito."],
["Let's split the bill.","Dividamos la cuenta."],
["Keep the change.","Quédese con el cambio."],
["This is delicious!","¡Esto está delicioso!"],
["It tastes great.","Sabe muy bien."],
["It's too spicy for me.","Está muy picante para mí."],
["I'm full.","Estoy lleno."],
["I'm on a diet.","Estoy a dieta."],
["I'm a vegetarian.","Soy vegetariano."],
["I'm allergic to peanuts.","Soy alérgico al maní."],
["Enjoy your meal!","¡Buen provecho!"],
["Would you like something to drink?","¿Quieres algo de tomar?"],
["Water is fine, thanks.","Agua está bien, gracias."],
["Cheers!","¡Salud!"],
["Breakfast is ready.","El desayuno está listo."],
["Dinner is served.","La cena está servida."],
["Help yourself to anything.","Toma lo que quieras."],
["Do you want seconds?","¿Quieres repetir?"],
["How much is it?","¿Cuánto cuesta?"],
["How much do I owe you?","¿Cuánto te debo?"],
["That's too expensive.","Está muy caro."],
["That's a good price.","Es un buen precio."],
["It's on sale.","Está en oferta."],
["Do you have this in another size?","¿Tienes esto en otra talla?"],
["Can I try it on?","¿Me lo puedo probar?"],
["It fits perfectly.","Me queda perfecto."],
["It doesn't fit.","No me queda."],
["I'll take it.","Me lo llevo."],
["I'm just looking, thanks.","Solo estoy mirando, gracias."],
["Do you take credit cards?","¿Aceptan tarjetas de crédito?"],
["Cash or card?","¿Efectivo o tarjeta?"],
["Can I get a receipt?","¿Me das el recibo?"],
["Can I return this?","¿Puedo devolver esto?"],
["It's out of stock.","Está agotado."],
["Where's the fitting room?","¿Dónde está el probador?"],
["Anything else for you?","¿Algo más para usted?"],
["That's all, thanks.","Eso es todo, gracias."],
["What are you looking for?","¿Qué estás buscando?"],
["I'm looking for a gift.","Estoy buscando un regalo."],
["Excuse me, where is the bathroom?","Disculpa, ¿dónde está el baño?"],
["How do I get there?","¿Cómo llego allá?"],
["Is it far from here?","¿Queda lejos de aquí?"],
["It's really close.","Queda muy cerca."],
["It's within walking distance.","Se puede ir caminando."],
["Go straight ahead.","Sigue derecho."],
["Turn left at the corner.","Gira a la izquierda en la esquina."],
["Turn right at the light.","Gira a la derecha en el semáforo."],
["It's next to the bank.","Queda al lado del banco."],
["It's across the street.","Está cruzando la calle."],
["It's on the second floor.","Está en el segundo piso."],
["You can't miss it.","No tiene pérdida."],
["I'm lost, can you help me?","Estoy perdido, ¿me ayudas?"],
["Where's the nearest station?","¿Dónde está la estación más cercana?"],
["Which bus goes downtown?","¿Qué bus va al centro?"],
["Where do I get off?","¿Dónde me bajo?"],
["This is my stop.","Esta es mi parada."],
["How long does it take?","¿Cuánto se demora?"],
["It takes about ten minutes.","Se demora unos diez minutos."],
["Are we there yet?","¿Ya llegamos?"],
["We're here!","¡Llegamos!"],
["Where did you park?","¿Dónde parqueaste?"],
["Can you give me a ride?","¿Me das un aventón?"],
["Buckle up.","Ponte el cinturón."],
["Slow down!","¡Baja la velocidad!"],
["We're almost out of gas.","Casi no tenemos gasolina."],
["I missed the bus.","Perdí el bus."],
["The traffic is terrible.","El tráfico está terrible."],
["What's the weather like?","¿Cómo está el clima?"],
["It's sunny today.","Hoy está soleado."],
["It's raining.","Está lloviendo."],
["It's pouring outside.","Está lloviendo a cántaros."],
["It looks like rain.","Parece que va a llover."],
["Take an umbrella.","Lleva paraguas."],
["It's freezing outside.","Está helado afuera."],
["It's really hot today.","Hoy hace mucho calor."],
["It's a beautiful day.","Es un día hermoso."],
["The weather is perfect.","El clima está perfecto."],
["It's cloudy.","Está nublado."],
["It's windy today.","Hoy hace viento."],
["What's the forecast?","¿Cuál es el pronóstico?"],
["Summer is coming.","Se acerca el verano."],
["I love this weather.","Me encanta este clima."],
["I have a headache.","Me duele la cabeza."],
["I have a stomachache.","Me duele el estómago."],
["My throat hurts.","Me duele la garganta."],
["I have a cold.","Estoy resfriado."],
["I have a fever.","Tengo fiebre."],
["I feel dizzy.","Me siento mareado."],
["I need to see a doctor.","Necesito ver a un médico."],
["Call a doctor!","¡Llama a un médico!"],
["Take this medicine.","Toma esta medicina."],
["Get some rest.","Descansa un poco."],
["Drink plenty of water.","Toma mucha agua."],
["Feel better soon!","¡Que te mejores pronto!"],
["How are you feeling?","¿Cómo te sientes?"],
["I'm feeling better.","Me siento mejor."],
["Are you hurt?","¿Estás herido?"],
["It's just a scratch.","Es solo un rasguño."],
["I twisted my ankle.","Me torcí el tobillo."],
["Do you have insurance?","¿Tienes seguro?"],
["I need a pharmacy.","Necesito una farmacia."],
["Stay healthy!","¡Mantente sano!"],
["I have a lot of work.","Tengo mucho trabajo."],
["I'm working on it.","Estoy trabajando en eso."],
["I finished my work.","Terminé mi trabajo."],
["I have a meeting.","Tengo una reunión."],
["I'll send you an email.","Te mando un correo."],
["Can we talk in private?","¿Podemos hablar en privado?"],
["What time do you get off?","¿A qué hora sales?"],
["I get off at five.","Salgo a las cinco."],
["I'm off today.","Hoy estoy libre."],
["I have the day off.","Tengo el día libre."],
["I got a new job!","¡Conseguí un nuevo trabajo!"],
["I got promoted.","Me ascendieron."],
["I quit my job.","Renuncié a mi trabajo."],
["I'm looking for a job.","Estoy buscando trabajo."],
["How's the new job?","¿Qué tal el nuevo trabajo?"],
["It's due tomorrow.","Se entrega mañana."],
["I'm behind schedule.","Voy atrasado."],
["Let's take a break.","Tomemos un descanso."],
["Break time is over.","Se acabó el descanso."],
["Back to work.","De vuelta al trabajo."],
["I have homework to do.","Tengo tarea que hacer."],
["Did you do your homework?","¿Hiciste la tarea?"],
["I passed the exam!","¡Pasé el examen!"],
["I failed the test.","Perdí el examen."],
["I have class today.","Hoy tengo clase."],
["Class is canceled.","Se canceló la clase."],
["What did you study?","¿Qué estudiaste?"],
["I'm studying English.","Estoy estudiando inglés."],
["Can I copy your notes?","¿Me prestas tus apuntes?"],
["Raise your hand.","Levanta la mano."],
["Any questions?","¿Alguna pregunta?"],
["I have a question.","Tengo una pregunta."],
["The answer is correct.","La respuesta es correcta."],
["Good question.","Buena pregunta."],
["Pay attention in class.","Presta atención en clase."],
["I learned something new.","Aprendí algo nuevo."],
["Teach me how to do it.","Enséñame cómo hacerlo."],
["You learn fast.","Aprendes rápido."],
["Keep practicing.","Sigue practicando."],
["Repeat after me.","Repite después de mí."],
["I'm home!","¡Llegué a casa!"],
["Welcome home.","Bienvenido a casa."],
["Did you lock the door?","¿Cerraste la puerta con llave?"],
["The door is open.","La puerta está abierta."],
["Close the door, please.","Cierra la puerta, por favor."],
["Time to wake up!","¡Hora de despertar!"],
["Wake up, sleepyhead!","¡Despierta, dormilón!"],
["I just woke up.","Me acabo de despertar."],
["I overslept.","Me quedé dormido."],
["Go take a shower.","Ve a bañarte."],
["I need a shower.","Necesito bañarme."],
["Brush your teeth.","Cepíllate los dientes."],
["Get dressed.","Vístete."],
["Make your bed.","Tiende tu cama."],
["Clean your room.","Ordena tu cuarto."],
["The house is a mess.","La casa está hecha un desastre."],
["I'll do the dishes.","Yo lavo los platos."],
["Take out the trash.","Saca la basura."],
["I'm doing laundry.","Estoy lavando la ropa."],
["Dinner's almost ready.","La cena está casi lista."],
["Set the table.","Pon la mesa."],
["Turn off the TV.","Apaga el televisor."],
["What's on TV?","¿Qué dan en la tele?"],
["I'm watching a movie.","Estoy viendo una película."],
["Lower the volume.","Baja el volumen."],
["It's time for bed.","Es hora de dormir."],
["Go to sleep.","Vete a dormir."],
["Sweet dreams.","Dulces sueños."],
["Did you feed the cat?","¿Le diste comida al gato?"],
["Water the plants.","Riega las plantas."],
["Can I have your number?","¿Me das tu número?"],
["Call me later.","Llámame más tarde."],
["Text me when you arrive.","Escríbeme cuando llegues."],
["I'll call you back.","Te devuelvo la llamada."],
["Who's calling?","¿Quién llama?"],
["Hold on, please.","Espera en línea, por favor."],
["You're breaking up.","Se te corta la llamada."],
["I can't hear you.","No te escucho."],
["Can you hear me now?","¿Me escuchas ahora?"],
["My phone is dying.","Se me está apagando el celular."],
["My battery is low.","Tengo poca batería."],
["I need a charger.","Necesito un cargador."],
["My phone is dead.","Se me apagó el celular."],
["I lost my phone.","Perdí mi celular."],
["Send me the link.","Mándame el enlace."],
["Send me a photo.","Mándame una foto."],
["Did you get my message?","¿Te llegó mi mensaje?"],
["I saw your message.","Vi tu mensaje."],
["Sorry, I just saw this.","Perdón, apenas veo esto."],
["What's the wifi password?","¿Cuál es la clave del wifi?"],
["The internet is down.","Se cayó el internet."],
["The internet is really slow.","El internet está muy lento."],
["Restart your computer.","Reinicia tu computador."],
["It's not working.","No está funcionando."],
["It works now!","¡Ya funciona!"],
["Turn it off and on again.","Apágalo y préndelo otra vez."],
["Update the app.","Actualiza la aplicación."],
["Download this app.","Descarga esta aplicación."],
["Delete that file.","Borra ese archivo."],
["Save your progress.","Guarda tu progreso."],
["I forgot my password.","Olvidé mi contraseña."],
["Log in to your account.","Inicia sesión en tu cuenta."],
["Follow me on Instagram.","Sígueme en Instagram."],
["I'll add you.","Te agrego."],
["Add me as a friend.","Agrégame como amigo."],
["Accept my friend request.","Acepta mi solicitud de amistad."],
["I sent you a friend request.","Te mandé solicitud de amistad."],
["Do you want to play?","¿Quieres jugar?"],
["Let's play a game.","Juguemos algo."],
["One more game?","¿Otra partida?"],
["Game over.","Fin del juego."],
["You win!","¡Ganaste!"],
["You lose.","Perdiste."],
["I won the match!","¡Gané la partida!"],
["We lost again.","Perdimos otra vez."],
["Good game!","¡Buen juego!"],
["Nice shot!","¡Buen tiro!"],
["Nice move!","¡Buena jugada!"],
["That was clutch!","¡Eso fue en el momento justo!"],
["You're so good at this.","Eres muy bueno en esto."],
["I'm new to this game.","Soy nuevo en este juego."],
["How do I play this?","¿Cómo se juega esto?"],
["What are the controls?","¿Cuáles son los controles?"],
["Which server are you on?","¿En qué servidor estás?"],
["Join my world.","Únete a mi mundo."],
["Invite me to your world.","Invítame a tu mundo."],
["Send me an invite.","Mándame una invitación."],
["I'll join you in a second.","Ya me uno contigo."],
["Wait for me in the lobby.","Espérame en el lobby."],
["Let's change the map.","Cambiemos de mapa."],
["This map is huge.","Este mapa es enorme."],
["I love this world.","Me encanta este mundo."],
["This place is awesome.","Este lugar es genial."],
["Your avatar is so cool.","Tu avatar está genial."],
["Where did you get that avatar?","¿De dónde sacaste ese avatar?"],
["Nice avatar!","¡Buen avatar!"],
["Can you see me?","¿Me puedes ver?"],
["Can you hear me, guys?","¿Me escuchan, chicos?"],
["My mic is muted.","Mi micrófono está silenciado."],
["Unmute your mic.","Activa tu micrófono."],
["Your mic is really loud.","Tu micrófono suena muy duro."],
["You're lagging.","Tienes lag."],
["The game is lagging.","El juego tiene lag."],
["My game crashed.","Se me cerró el juego."],
["I got disconnected.","Me desconecté."],
["Let me reconnect.","Déjame reconectar."],
["I'm streaming right now.","Estoy transmitiendo en vivo."],
["I saw your stream.","Vi tu transmisión."],
["Let's take a screenshot.","Tomemos una captura."],
["Say cheese!","¡Digan whisky!"],
["Let's explore this world.","Exploremos este mundo."],
["Follow me, I know the way.","Síganme, yo conozco el camino."],
["Don't fall!","¡No te caigas!"],
["Jump over here.","Salta acá."],
["Come to my instance.","Ven a mi instancia."],
["This instance is full.","Esta instancia está llena."],
["Let's make a private room.","Hagamos una sala privada."],
["Who's your favorite artist?","¿Cuál es tu artista favorito?"],
["What music do you like?","¿Qué música te gusta?"],
["I love this song!","¡Me encanta esta canción!"],
["This is my favorite song.","Esta es mi canción favorita."],
["Turn up the music!","¡Sube la música!"],
["What song is this?","¿Qué canción es esta?"],
["Have you heard this song?","¿Has oído esta canción?"],
["Put on some music.","Pon algo de música."],
["The beat is amazing.","El ritmo es increíble."],
["I can't stop listening to it.","No puedo dejar de escucharla."],
["It's stuck in my head.","La tengo pegada en la cabeza."],
["Do you play any instruments?","¿Tocas algún instrumento?"],
["I play the guitar.","Toco la guitarra."],
["Can you sing?","¿Sabes cantar?"],
["Let's sing together.","Cantemos juntos."],
["You have a great voice.","Tienes una gran voz."],
["I love singing.","Me encanta cantar."],
["I'm a terrible singer.","Canto terrible."],
["Let's go to a concert.","Vamos a un concierto."],
["The concert was amazing.","El concierto estuvo increíble."],
["Do you know the lyrics?","¿Te sabes la letra?"],
["I know it by heart.","Me la sé de memoria."],
["What does this song mean?","¿Qué significa esta canción?"],
["Music brings people together.","La música une a la gente."],
["Let's dance!","¡Bailemos!"],
["This is my family.","Esta es mi familia."],
["I have two brothers.","Tengo dos hermanos."],
["Do you have any siblings?","¿Tienes hermanos?"],
["I'm an only child.","Soy hijo único."],
["My parents are strict.","Mis padres son estrictos."],
["I live with my parents.","Vivo con mis padres."],
["Family comes first.","La familia es primero."],
["He's my best friend.","Él es mi mejor amigo."],
["She's like a sister to me.","Ella es como mi hermana."],
["We grew up together.","Crecimos juntos."],
["We've been friends for years.","Somos amigos hace años."],
["You're a true friend.","Eres un verdadero amigo."],
["I've got your back.","Yo te cubro, cuenta conmigo."],
["You can count on me.","Puedes contar conmigo."],
["That's what friends are for.","Para eso son los amigos."],
["Let's stay friends forever.","Seamos amigos por siempre."],
["I made a new friend.","Hice un nuevo amigo."],
["Do you have a girlfriend?","¿Tienes novia?"],
["Do you have a boyfriend?","¿Tienes novio?"],
["I'm single.","Estoy soltero."],
["I have a crush on someone.","Alguien me gusta."],
["I'm in love.","Estoy enamorado."],
["Help!","¡Ayuda!"],
["Help me, please!","¡Ayúdame, por favor!"],
["Call the police!","¡Llama a la policía!"],
["It's an emergency.","Es una emergencia."],
["There's been an accident.","Hubo un accidente."],
["Is everyone okay?","¿Están todos bien?"],
["I need help right now.","Necesito ayuda ya."],
["Something's wrong.","Algo anda mal."],
["Don't move.","No te muevas."],
["Stay calm.","Mantén la calma."],
["I lost my wallet.","Perdí mi billetera."],
["I lost my keys.","Perdí mis llaves."],
["I locked myself out.","Me quedé por fuera, sin llaves."],
["My car broke down.","Se me dañó el carro."],
["I ran out of money.","Me quedé sin dinero."],
["I got scammed.","Me estafaron."],
["That's against the rules.","Eso va contra las reglas."],
["You're breaking the rules.","Estás rompiendo las reglas."],
["He got banned.","Lo banearon."],
["Report that player.","Reporta a ese jugador."],
["What time do we start?","¿A qué hora empezamos?"],
["It starts at seven.","Empieza a las siete."],
["It's five o'clock.","Son las cinco en punto."],
["It's half past two.","Son las dos y media."],
["It's a quarter to nine.","Son un cuarto para las nueve."],
["In five minutes.","En cinco minutos."],
["An hour ago.","Hace una hora."],
["Twice a week.","Dos veces por semana."],
["Every single day.","Todos los días sin falta."],
["Once a month.","Una vez al mes."],
["What's the date today?","¿Qué fecha es hoy?"],
["It's the first of May.","Es el primero de mayo."],
["My birthday is in June.","Mi cumpleaños es en junio."],
["Next week works.","La próxima semana me sirve."],
["Two years ago.","Hace dos años."],
["Since last year.","Desde el año pasado."],
["How many do you need?","¿Cuántos necesitas?"],
["Just a few.","Solo unos pocos."],
["A couple of times.","Un par de veces."],
["More than enough.","Más que suficiente."],
["Wake me up early.","Despiértame temprano."],
["Don't stay up late.","No te trasnoches."],
["I stayed up all night.","Me quedé despierto toda la noche."],
["Let's get started.","Empecemos."],
["Let's get out of here.","Salgamos de aquí."],
["Get out of the way!","¡Quítate del camino!"],
["Get over here!","¡Ven acá ya!"],
["I can't get over it.","No lo puedo superar."],
["It turns out that...","Resulta que..."],
["Figure it out.","Resuélvelo tú."],
["I figured it out!","¡Lo descifré!"],
["It doesn't add up.","Algo no cuadra."],
["Look it up online.","Búscalo en internet."],
["Check it out later.","Míralo más tarde."],
["Watch your step.","Cuidado por dónde pisas."],
["Hold my hand.","Toma mi mano."],
["Give it back!","¡Devuélvelo!"],
["Put it back.","Ponlo donde estaba."],
["Turn around.","Date la vuelta."],
["Move over a little.","Córrete un poquito."],
["Scoot over.","Hazte a un lado."],
["Back off!","¡Aléjate!"],
["Stay here.","Quédate aquí."],
["Stay with me.","Quédate conmigo."],
["Don't leave me alone.","No me dejes solo."],
["Where were you?","¿Dónde estabas?"],
["I was about to leave.","Estaba a punto de irme."],
["I changed my mind.","Cambié de opinión."],
["Make up your mind.","Decídete de una vez."],
["It slipped my mind.","Se me pasó por completo."],
["I did it on purpose.","Lo hice a propósito."],
["It was an accident.","Fue un accidente."],
["It wasn't me.","No fui yo."],
["It's all your fault.","Todo es tu culpa."],
["It's not my fault.","No es mi culpa."],
["Whose fault is it?","¿De quién es la culpa?"],
["Stop blaming me.","Deja de culparme."],
["I take it back.","Retiro lo dicho."],
["I didn't mean to.","No fue mi intención."],
["Let it go.","Déjalo ir."],
["Let me handle it.","Déjame encargarme."],
["I'll take care of it.","Yo me encargo."],
["Leave it to me.","Déjamelo a mí."],
["Consider it done.","Dalo por hecho."],
["Whatever it takes.","Lo que sea necesario."],
["No matter what.","Pase lo que pase."],
["At any cost.","A como dé lugar."],
["I did my best.","Hice mi mejor esfuerzo."],
["It was worth a try.","Valió la pena intentarlo."],
["Nothing to lose.","Nada que perder."],
["Take a chance.","Arriésgate."],
["Go for it!","¡Ve por ello!"],
["Don't hold back.","No te contengas."],
["Give it your all.","Dalo todo."],
["You nailed it!","¡Le diste al clavo!"],
["You crushed it!","¡La rompiste!"],
["That was epic!","¡Eso fue épico!"],
["Best day ever!","¡El mejor día de todos!"],
["Worst day ever.","El peor día de todos."],
["Today is my lucky day.","Hoy es mi día de suerte."],
["Just my luck.","Típica mala suerte la mía."],
["What are the odds?","¿Qué probabilidades había?"],
["I knew it!","¡Lo sabía!"],
["I told you so.","Te lo dije."],
["You were right.","Tenías razón."],
["I was wrong.","Estaba equivocado."],
["My mistake, sorry.","Error mío, perdón."],
["It won't happen again.","No volverá a pasar."],
["Lesson learned.","Lección aprendida."],
["Live and learn.","Vivir y aprender."],
["Now I get it!","¡Ahora sí entiendo!"],
["Oh, I see.","Ah, ya veo."],
["That explains it.","Eso lo explica."],
["Now it makes sense.","Ahora tiene sentido."],
["Wait, what?","Espera, ¿qué?"],
["Say that again?","¿Cómo dijiste?"],
["I didn't catch that.","No entendí eso."],
["Come again?","¿Perdón? ¿Qué dijiste?"],
["Speak up, please.","Habla más fuerte, por favor."],
["Never heard of it.","Nunca lo había oído."],
["Sounds familiar.","Me suena familiar."],
["It rings a bell.","Me suena de algo."],
["On the tip of my tongue.","Lo tengo en la punta de la lengua."],
["I can't remember.","No me acuerdo."],
["Now I remember!","¡Ya me acordé!"],
["How could I forget?","¿Cómo pude olvidarlo?"],
["Don't remind me.","Ni me lo recuerdes."],
["Those were the days.","Qué tiempos aquellos."],
["Good times!","¡Buenos tiempos!"],
["I'll never forget it.","Nunca lo olvidaré."],
["Memories last forever.","Los recuerdos duran para siempre."],
["Home sweet home.","Hogar, dulce hogar."],
["There's no place like home.","No hay lugar como el hogar."],
["Dream big!","¡Sueña en grande!"],
["Follow your dreams.","Sigue tus sueños."],
["Anything is possible.","Todo es posible."],
["The sky is the limit.","El cielo es el límite."],
["Believe in yourself.","Cree en ti mismo."],
["Be yourself.","Sé tú mismo."],
["Stay positive.","Mantente positivo."],
["Enjoy the moment.","Disfruta el momento."],
["Life is short.","La vida es corta."],
["Make it count.","Haz que valga la pena."],
["One day at a time.","Un día a la vez."],
["Everything happens for a reason.","Todo pasa por algo."],
["When in doubt, ask.","Ante la duda, pregunta."],
["Actions speak louder than words.","Las acciones dicen más que las palabras."],
["Better late than never.","Más vale tarde que nunca."],
["See you next time.","Nos vemos la próxima."],
["It's my treat.","Yo pago, es mi invitación."]
];
